name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:  # 允许手动运行

permissions:
  contents: write
  packages: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有 commit 和 tag

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot  # 👈 添加 --snapshot 跳过 tag 检查
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
